sudo: false

language: go

go:
  - 1.8.x

env:
  global:
    - HUGO_VERSION=0.22

before_install:
  - mkdir -p $HOME/gopath/bin
  - curl https://glide.sh/get | sh
  - mkdir -p $HOME/local/bin
  - wget -O - "https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | tar xz -C ${TMPDIR-/tmp}
  - mv ${TMPDIR-/tmp}/hugo $HOME/local/bin/hugo
  - $HOME/local/bin/hugo version

install:
  - glide install

after_script:
  - cd $TRAVIS_BUILD_DIR/website
  - $HOME/local/bin/hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/website/public
  github_token: $GITHUB_API_KEY
  on:
    branch: master
