baseurl = "https://mqllab.github.io/MUKLA/"
languageCode = "en-au"
metadataformat = "yaml"
title = "MUKLA: MQL4 package manager for MetaTrader 4."
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = ""

[params]
	name = "MUKLA"
	description = "MQL4 package manager for MetaTrader 4."

	github_user   = "MQLLAB"
	github_repo   = "MUKLA"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"

	github_button  = true
	travis_button  = true
	codecov_button = true
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[Eneset Group Trust](https://www.eneset.com)"
	show_powered_by = false
